### ISSUE TITLE
Definitions for type-checking

### ISSUE THREAD

**Issue by lauri-codes** [FAIRmat-NFDI/cookiecutter-nomad-plugin#15]
Just a small question: why was this necessary: 

```python
from typing import (
    TYPE_CHECKING,
)

if TYPE_CHECKING:
    from nomad.datamodel.datamodel import (
        EntryArchive,
    )
    from structlog.stdlib import (
        BoundLogger,
    )
```

Was this introduced to avoid some import problems, or is this the recommended way instead of importing the actual definitions?

**Comment by blueraft** [comment]
This was added because @hampusnasstrom requested this.

But this is also the recommended way to add type annotations to avoid circular imports, see [blog](https://vickiboykis.com/2023/12/11/why-if-type_checking/) post on this.

**Comment by lauri-codes** [comment]
I was just wondering, because the new plugin layout is designed to avoid cyclical import as best as we can, and if there was an actual problem with some schema. @hampusnasstrom: Did you experience some issues with cyclical imports?

**Comment by lauri-codes** [comment]
I see. I would then argue that we can simplify this in the new system by simply importing these two directly. The new system will load the plugins in a way that should prevent the cyclical imports.

Could you @blueraft do this simplification for all entry points? Just do both imports at the top regularly. If we then later still get some unfixable problems with the imports, then we can always come back to this solution.

**Comment by hampusnasstrom** [comment]
We just need to make sure that the IDEs (VScode at least) understands this for type hinting.

**Comment by blueraft** [comment]
LSP works fine 
![image](https://github.com/FAIRmat-NFDI/cookiecutter-nomad-plugin/assets/11220895/d06a4049-ed6d-4a8d-9946-ec78d9f35880)

But we will have to pull in `structlog` as a main dependency now since it's not a conditional import anymore.

```shell
❯ python
Python 3.9.10 (main, Feb  6 2024, 15:20:00)
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nomad_foobar.schema_packages import mypackage
>>> mypackage.load()
Schema is deprecated, use plugins. ()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ahmedilyas/cookiecutter-nomad-plugin/nomad-foobar/.venv/lib/python3.9/site-packages/nomad_foobar/schema_packages/__init__.py", line 9, in load
    from nomad_foobar.schema_packages.mypackage import m_package
  File "/home/ahmedilyas/cookiecutter-nomad-plugin/nomad-foobar/.venv/lib/python3.9/site-packages/nomad_foobar/schema_packages/mypackage.py", line 6, in <module>
    from structlog.stdlib import BoundLogger
ModuleNotFoundError: No module named 'structlog'
```

**Comment by lauri-codes** [comment]
Yes, `structlog` should be a default dependency.
